drop extension if exists "pg_net";

create type "public"."course" as enum ('Course A', 'Course B', 'Course C');

create type "public"."section" as enum ('A', 'B', 'C');

create type "public"."year" as enum ('1', '2', '3', '4');


  create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
      );



  create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "email" text,
    "first_name" text,
    "middle_name" text,
    "last_name" text,
    "suffix" text,
    "balance" double precision,
    "course" course,
    "year" year,
    "section" section
      );


CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";


